### Create category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Category 1",
  "description": "Category 1 description"
}

### List categories
GET http://localhost:3000/categories

### Get category
GET http://localhost:3000/categories/adb3e3e3-3e3e-3e3e-3e3e-3e3e3e3e3e3e